  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81558cf5f8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/unittest-xml-reporting/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81558cf6a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/unittest-xml-reporting/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81558cfbe0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/unittest-xml-reporting/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81558cf048>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/unittest-xml-reporting/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81558cf0f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/unittest-xml-reporting/
  Could not find a version that satisfies the requirement unittest-xml-reporting (from versions: )
No matching distribution found for unittest-xml-reporting
