<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="unittest/loader.py" name="unittest.loader._FailedTest-20190430091547" skipped="0" tests="1" time="0.010" timestamp="2019-04-30T09:15:47">
	<testcase classname="unittest.loader._FailedTest" file="/usr/lib/python3.6/unittest/loader.py" line="33" name="OBD_tests" time="0.010" timestamp="2019-04-30T09:15:47">
		<error message="Failed to import test module: OBD_tests
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/unittest/loader.py&quot;, line 153, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/home/not-yeshwanth-reddy/Documents/Sem6/Capstone/OBD/src/unittest/python/OBD_tests.py&quot;, line 4, in &lt;module&gt;
    import OBD
  File &quot;/home/not-yeshwanth-reddy/Documents/Sem6/Capstone/OBD/src/main/python/OBD.py&quot;, line 25, in &lt;module&gt;
    import cv2
ModuleNotFoundError: No module named 'cv2'
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: OBD_tests
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/not-yeshwanth-reddy/Documents/Sem6/Capstone/OBD/src/unittest/python/OBD_tests.py", line 4, in <module>
    import OBD
  File "/home/not-yeshwanth-reddy/Documents/Sem6/Capstone/OBD/src/main/python/OBD.py", line 25, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
